// Auto-generated by s4extract.
using UnityEngine;

public class S4Recolorable : MonoBehaviour
{
    [System.Serializable]
    public struct SwatchVariant
    {
        public string swatchName;
        public Material[] subMeshMaterials; // material for each renderer
    }

    public SwatchVariant[] swatches;
    public Renderer[] targetRenderers;

    public void Recolor(int index)
    {
        if (swatches == null || index < 0 || index >= swatches.Length) return;
        if (targetRenderers == null) return;
        
        var variant = swatches[index];
        for (int i = 0; i < targetRenderers.Length; i++)
        {
            if (targetRenderers[i] == null || i >= variant.subMeshMaterials.Length) continue;
            if (variant.subMeshMaterials[i] == null) continue;
            
            // Assign the material
            targetRenderers[i].sharedMaterial = variant.subMeshMaterials[i];
        }
    }
}
