// s4extract batch fixer (Unity 6 compatible).
// Auto-generated by s4extract. Patched:
//   * actually invokes S4ColliderOptimizer.OptimizeForBatch via reflection
//     (works regardless of which Editor folder the optimizer is in),
//   * recursive search for S4Extract_Data under Assets/
//     (old script required it at Assets/S4Extract_Data exactly),
//   * auto-enables Read/Write on collider meshes,
//   * guarantees EditorUtility.ClearProgressBar() + final "Done!" log via
//     try/finally even if an exception escapes.
#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.SceneManagement;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System;
using System.Reflection;

[InitializeOnLoad]
public static class S4ExtractBatchFixer
{
    const string OptimizerTypeName = "S4ColliderOptimizer";

    static S4ExtractBatchFixer()
    {
        EditorApplication.delayCall += () =>
        {
            if (EditorPrefs.GetBool("S4Extract_FirstRun", true))
            {
                EditorPrefs.SetBool("S4Extract_FirstRun", false);
                string dataDir = ResolveDataDir();
                if (dataDir != null)
                {
                    int count = Directory.GetFiles(dataDir, "*.json").Length;
                    if (count > 0)
                        Debug.Log($"s4extract: Batch fixer loaded. Found {count} export(s) in {dataDir}. " +
                                   "Use Tools/s4extract → Fix All Exports.");
                    else
                        Debug.Log("s4extract: Batch fixer loaded but no .json exports found in " + dataDir);
                }
                else
                {
                    Debug.Log("s4extract: Batch fixer loaded. No S4Extract_Data folder found under Assets yet; export something first.");
                }
            }
        };
    }

    static string FindFolderRecursive(string root, string folderName)
    {
        try
        {
            foreach (string dir in Directory.GetDirectories(root))
            {
                if (Path.GetFileName(dir) == folderName) return dir;
                string deeper = FindFolderRecursive(dir, folderName);
                if (deeper != null) return deeper;
            }
        }
        catch { /* access denied on Library/Temp subfolders – ignore */ }
        return null;
    }

    static string ResolveDataDir()
    {
        string direct = Path.Combine(Application.dataPath, "S4Extract_Data");
        if (Directory.Exists(direct)) return direct;
        return FindFolderRecursive(Application.dataPath, "S4Extract_Data");
    }

    [MenuItem("Tools/s4extract/Fix All Exports")]
    public static void FixAllExports()
    {
        Debug.Log("s4extract: Fix All Exports invoked.");
        string dataDir = ResolveDataDir();
        if (dataDir == null)
        {
            Debug.LogError("s4extract: No S4Extract_Data folder found under Assets/. " +
                           "Run the python extractor first so JSON + OBJ/FBX are written under Assets/<your folder>/S4Extract_Data.");
            EditorUtility.ClearProgressBar();
            return;
        }

        string[] jsonFiles = Directory.GetFiles(dataDir, "*.json");
        if (jsonFiles.Length == 0)
        {
            Debug.LogWarning("s4extract: No export data (*.json) found in " + dataDir);
            EditorUtility.ClearProgressBar();
            return;
        }
        Debug.Log($"s4extract: Processing {jsonFiles.Length} export(s) from {dataDir} ...");

        EnsureColliderMeshesReadable();

        MethodInfo optimizeMethod = FindOptimizeBatchMethod();
        if (optimizeMethod == null)
            Debug.LogWarning("s4extract: S4ColliderOptimizer.OptimizeForBatch not found. " +
                             "Place S4ColliderOptimizer.cs anywhere under Assets/.../Editor/ to enable collider simplification.");
        else
            Debug.Log($"s4extract: Found collider optimizer at {optimizeMethod.DeclaringType.FullName}.{optimizeMethod.Name}");

        int totalFixed = 0, totalAssigned = 0, totalPrefabs = 0, totalOptimized = 0;
        int totalFailed = 0;
        bool cancelled = false;

        try
        {
            for (int exportIndex = 0; exportIndex < jsonFiles.Length; exportIndex++)
            {
                string jsonFile = jsonFiles[exportIndex];
                string assetDisplayName = Path.GetFileNameWithoutExtension(jsonFile);
                if (EditorUtility.DisplayCancelableProgressBar(
                    "s4extract: Fix All Exports",
                    $"{exportIndex + 1}/{jsonFiles.Length}  {assetDisplayName}",
                    (float)exportIndex / jsonFiles.Length))
                {
                    cancelled = true;
                    Debug.LogWarning($"s4extract: Batch cancelled after {exportIndex} export(s).");
                    break;
                }

                string stage = "read JSON";
                try
                {
                    string json = File.ReadAllText(jsonFile);
                    var exportData = JsonUtility.FromJson<ExportData>(json);
                    if (exportData == null)
                        throw new Exception("JsonUtility returned null ExportData (possible parse error or unexpected JSON structure).");
                    NormalizeExportData(exportData);

                    stage = "process materials";
                    int fixedCount = ProcessMaterials(exportData);

                    stage = "assign materials";
                    int assigned = AssignMaterialsToMeshes(exportData);

                    stage = "create READY prefab + optimize colliders";
                    bool ranOptimizer;
                    string readyPrefab = CreateReadyPrefab(exportData, jsonFile, optimizeMethod, out ranOptimizer);

                    totalFixed += fixedCount;
                    totalAssigned += assigned;
                    if (!string.IsNullOrEmpty(readyPrefab))
                    {
                        totalPrefabs++;
                        if (ranOptimizer) totalOptimized++;
                    }
                }
                catch (Exception e)
                {
                    totalFailed++;
                    Debug.LogError($"s4extract: Failed to process {Path.GetFileName(jsonFile)} at stage '{stage}':\n{e}");
                }
            }
        }
        finally
        {
            EditorUtility.ClearProgressBar();
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log($"s4extract: Done! Fixed {totalFixed} material(s), assigned {totalAssigned} renderer(s), " +
                      $"created {totalPrefabs} READY prefab(s), collider optimization ran on {totalOptimized}, " +
                      $"failed {totalFailed}{(cancelled ? " (cancelled)" : "")}.");
        }
    }

    [MenuItem("Tools/s4extract/Fix Last Export")]
    public static void FixLastExport()
    {
        string dataDir = ResolveDataDir();
        if (dataDir == null)
        {
            Debug.LogWarning("s4extract: No S4Extract_Data folder found.");
            return;
        }
        string[] jsonFiles = Directory.GetFiles(dataDir, "*.json");
        if (jsonFiles.Length == 0)
        {
            Debug.LogWarning("s4extract: No export data found.");
            return;
        }
        string lastFile = jsonFiles.OrderByDescending(f => f).First();

        try
        {
            EnsureColliderMeshesReadable();
            MethodInfo optimizeMethod = FindOptimizeBatchMethod();

            string json = File.ReadAllText(lastFile);
            var exportData = JsonUtility.FromJson<ExportData>(json);
            if (exportData == null) throw new Exception("JsonUtility returned null ExportData");
            NormalizeExportData(exportData);

            int fixedCount = ProcessMaterials(exportData);
            int assigned = AssignMaterialsToMeshes(exportData);
            bool ranOptimizer;
            string readyPrefab = CreateReadyPrefab(exportData, lastFile, optimizeMethod, out ranOptimizer);

            AssetDatabase.SaveAssets();
            Debug.Log($"s4extract: Processed {Path.GetFileName(lastFile)}. Fixed {fixedCount} material(s), " +
                      $"assigned {assigned} renderer(s), prefab: {readyPrefab}, optimizer ran: {ranOptimizer}.");
        }
        catch (Exception e)
        {
            Debug.LogError($"s4extract: Failed on last export: {e}");
        }
        finally
        {
            EditorUtility.ClearProgressBar();
        }
    }

    // -------- Data structures --------

    [Serializable]
    public class ExportData
    {
        public string folderName;
        public string id;
        public string assetName;
        public MaterialEntry[] materials;
        public string[] meshNames;
        public string[] colliderAssets;
        public MeshMaterialEntry[] meshMaterials;
    }

    [Serializable]
    public class MaterialEntry
    {
        public string materialName;
        public string albedoName;
        public string normalName;
        public string maskName;
    }

    [Serializable]
    public class MeshMaterialEntry
    {
        public string meshName;
        public string materialName;
    }

    static void NormalizeExportData(ExportData data)
    {
        if (data.materials == null) data.materials = new MaterialEntry[0];
        if (data.meshNames == null) data.meshNames = new string[0];
        if (data.colliderAssets == null) data.colliderAssets = new string[0];
        if (data.meshMaterials == null) data.meshMaterials = new MeshMaterialEntry[0];
    }

    // -------- Core processing --------

    static int ProcessMaterials(ExportData data)
    {
        Shader shader = FindBestShader();
        if (shader == null)
        {
            Debug.LogWarning("s4extract: Could not find a suitable shader (HDRP/Lit, URP/Lit, Standard).");
            return 0;
        }
        int changed = 0;
        foreach (var entry in data.materials)
        {
            if (entry == null) continue;
            Material mat = FindMaterial(entry.materialName);
            Texture albedo = FindTexture(entry.albedoName);
            Texture normal = FindTexture(entry.normalName);
            Texture mask = FindTexture(entry.maskName);
            if (mat == null) continue;

            mat.shader = shader;
            if (albedo != null)
            {
                SetTex(mat, "_BaseColorMap", albedo);
                SetTex(mat, "_BaseMap", albedo);
                SetTex(mat, "_MainTex", albedo);
            }
            if (normal != null)
            {
                MakeNormalMap(normal);
                SetTex(mat, "_NormalMap", normal);
                SetTex(mat, "_BumpMap", normal);
                mat.EnableKeyword("_NORMALMAP");
                mat.EnableKeyword("_NORMALMAP_TANGENT_SPACE");
            }
            if (mask != null)
            {
                SetTex(mat, "_MaskMap", mask);
                SetTex(mat, "_MetallicGlossMap", mask);
            }
            SetColor(mat, "_BaseColor", Color.white);
            SetColor(mat, "_Color", Color.white);
            SetFloat(mat, "_Metallic", 0f);
            SetFloat(mat, "_Smoothness", 0.5f);
            SetFloat(mat, "_NormalScale", 1f);
            SetFloat(mat, "_BumpScale", 1f);
            SetFloat(mat, "_SurfaceType", 0f);
            SetFloat(mat, "_Surface", 0f);
            mat.renderQueue = -1;
            EditorUtility.SetDirty(mat);
            changed++;
        }
        return changed;
    }

    static int AssignMaterialsToMeshes(ExportData data)
    {
        if (data.materials.Length == 0 || data.meshNames.Length == 0) return 0;
        Material first = FindMaterial(data.materials[0].materialName);
        if (first == null) return 0;

        int assigned = 0;

#if UNITY_2023_1_OR_NEWER
        Renderer[] renderers = UnityEngine.Object.FindObjectsByType<Renderer>(FindObjectsInactive.Include, FindObjectsSortMode.None);
#else
        Renderer[] renderers = UnityEngine.Object.FindObjectsOfType<Renderer>(true);
#endif

        foreach (Renderer r in renderers)
        {
            if (r == null) continue;
            string goName = r.gameObject.name;
            Material target = FindPreferredMaterialForMesh(goName, data);
            if (target == null)
            {
                foreach (string mn in data.meshNames)
                {
                    if (goName == mn || goName.StartsWith(mn, StringComparison.Ordinal))
                    {
                        target = FindPreferredMaterialForMesh(mn, data) ?? first;
                        break;
                    }
                }
            }
            if (target == null) continue;
            Material[] mats = r.sharedMaterials;
            if (mats == null || mats.Length == 0) mats = new Material[] { target };
            for (int i = 0; i < mats.Length; i++) mats[i] = target;
            r.sharedMaterials = mats;
            EditorUtility.SetDirty(r);
            assigned++;
        }
        return assigned;
    }

    static Material FindPreferredMaterialForMesh(string meshName, ExportData data)
    {
        if (string.IsNullOrEmpty(meshName)) return null;
        foreach (var mm in data.meshMaterials)
        {
            if (mm == null) continue;
            if (meshName == mm.meshName || meshName.StartsWith(mm.meshName, StringComparison.Ordinal))
            {
                Material m = FindMaterial(mm.materialName);
                if (m != null) return m;
            }
        }
        return null;
    }

    static int GetLodIndex(string assetName)
    {
        if (string.IsNullOrEmpty(assetName)) return -1;
        string n = assetName.ToLowerInvariant();
        string[] markers = new string[] { "_lod", "mlod", "modl" };
        foreach (string marker in markers)
        {
            int at = n.LastIndexOf(marker, StringComparison.Ordinal);
            if (at < 0) continue;
            int pos = at + marker.Length;
            int value = 0, digits = 0;
            while (pos < n.Length && n[pos] >= '0' && n[pos] <= '9')
            {
                value = value * 10 + (n[pos] - '0');
                digits++; pos++;
            }
            if (digits > 0) return value;
        }
        return -1;
    }

    static string CreateReadyPrefab(ExportData data, string jsonPath, MethodInfo optimizeMethod, out bool ranOptimizer)
    {
        ranOptimizer = false;
        if (data.materials.Length == 0 || data.meshNames.Length == 0) return "";
        Material first = FindMaterial(data.materials[0].materialName);
        if (first == null) return "";
        string matPath = AssetDatabase.GetAssetPath(first);
        if (string.IsNullOrEmpty(matPath)) return "";
        string folder = Path.GetDirectoryName(matPath).Replace("\\", "/");
        string prefabPath = folder + "/" + data.assetName + "_READY.prefab";

        GameObject root = new GameObject(data.assetName + "_READY");
        try
        {
            var identity = root.AddComponent<S4Identity>();
            int idVal; if (!int.TryParse(data.id, out idVal)) idVal = 0;
            identity.id = idVal;
            identity.assetName = data.assetName;

            Rigidbody rb = root.GetComponent<Rigidbody>();
            if (rb == null) rb = root.AddComponent<Rigidbody>();
            rb.mass = 10f;
            rb.drag = 0.05f;
            rb.angularDrag = 0.05f;
            rb.useGravity = true;
            rb.isKinematic = false;
            rb.interpolation = RigidbodyInterpolation.Interpolate;
            rb.collisionDetectionMode = CollisionDetectionMode.ContinuousSpeculative;

            int added = 0;
            int collidersBefore = 0;
            foreach (string mn in data.meshNames)
            {
                GameObject model = FindModelAsset(mn);
                if (model == null)
                {
                    Debug.LogWarning($"s4extract[{data.assetName}]: model mesh '{mn}' not found in AssetDatabase; skipping.");
                    continue;
                }
                Material target = FindPreferredMaterialForMesh(mn, data) ?? first;
                GameObject child = (GameObject)PrefabUtility.InstantiatePrefab(model);
                if (child == null) child = UnityEngine.Object.Instantiate(model);
                if (child == null) continue;
                child.name = mn;
                child.transform.SetParent(root.transform, false);
                foreach (Renderer r in child.GetComponentsInChildren<Renderer>(true))
                {
                    if (r == null) continue;
                    Material[] mats = r.sharedMaterials;
                    if (mats == null || mats.Length == 0) mats = new Material[] { target };
                    for (int i = 0; i < mats.Length; i++) mats[i] = target;
                    r.sharedMaterials = mats;
                }
                added++;
            }

            // ---- Colliders ----
            if (data.colliderAssets != null && data.colliderAssets.Length > 0)
            {
                foreach (string ca in data.colliderAssets) AddColliderAsset(root, ca);
            }
            else
            {
                foreach (string mn in data.meshNames)
                {
                    if (GetLodIndex(mn) != 0) continue;
                    string[] guids = AssetDatabase.FindAssets(mn + "_collider t:GameObject");
                    foreach (string g in guids)
                    {
                        string p = AssetDatabase.GUIDToAssetPath(g);
                        if (string.IsNullOrEmpty(p)) continue;
                        GameObject colModel = AssetDatabase.LoadAssetAtPath<GameObject>(p);
                        AddColliderModel(root, colModel);
                    }
                }
            }
            collidersBefore = root.GetComponents<MeshCollider>().Length;

            // ---- LOD Group ----
            LODGroup lodGroup = root.AddComponent<LODGroup>();
            var lodRenderers = new Dictionary<int, List<Renderer>>();
            foreach (Transform child in root.transform)
            {
                if (child == null) continue;
                int lodIdx = GetLodIndex(child.name);
                if (lodIdx < 0) continue;
                foreach (Renderer r in child.GetComponentsInChildren<Renderer>(true))
                {
                    if (r == null) continue;
                    if (!lodRenderers.ContainsKey(lodIdx)) lodRenderers[lodIdx] = new List<Renderer>();
                    lodRenderers[lodIdx].Add(r);
                }
            }
            if (lodRenderers.Count > 0)
            {
                var keys = new List<int>(lodRenderers.Keys); keys.Sort();
                LOD[] lods = new LOD[keys.Count];
                float[] screenHeights = new float[] { 0.5f, 0.25f, 0.10f, 0.01f };
                for (int i = 0; i < keys.Count; i++)
                {
                    int k = keys[i];
                    float h = (i == keys.Count - 1) ? 0f : ((i < screenHeights.Length) ? screenHeights[i] : 0.01f);
                    lods[i] = new LOD(h, lodRenderers[k].ToArray());
                }
                lodGroup.SetLODs(lods);
                lodGroup.RecalculateBounds();
            }

            if (added == 0)
            {
                Debug.LogWarning($"s4extract[{data.assetName}]: no meshes were attached; skipping READY prefab.");
                return "";
            }

            // ---- Collider optimizer ----
            string optResult;
            if (optimizeMethod != null)
            {
                try
                {
                    object[] args = new object[] { root, 0.50f, 0.04f, 0.003f, 6f };
                    optResult = (string)optimizeMethod.Invoke(null, args);
                    ranOptimizer = true;
                }
                catch (TargetInvocationException tie)
                {
                    optResult = $"optimizer threw: {tie.InnerException}";
                    Debug.LogError($"s4extract[{data.assetName}]: collider optimizer threw:\n{tie.InnerException ?? tie as Exception}");
                }
                catch (Exception ex)
                {
                    optResult = $"optimizer invoke failed: {ex.Message}";
                    Debug.LogError($"s4extract[{data.assetName}]: collider optimizer invoke failed:\n{ex}");
                }
            }
            else
            {
                optResult = "S4ColliderOptimizer not found in project; keeping convex MeshColliders.";
            }

            int collidersAfter_Mesh  = root.GetComponentsInChildren<MeshCollider>(true).Length;
            int collidersAfter_Box   = root.GetComponentsInChildren<BoxCollider>(true).Length;
            int collidersAfter_Cap   = root.GetComponentsInChildren<CapsuleCollider>(true).Length;
            int collidersAfter_Sph   = root.GetComponentsInChildren<SphereCollider>(true).Length;
            Debug.Log($"s4extract[{data.assetName}]: colliders before={collidersBefore} convex MeshCollider(s); " +
                      $"after={collidersAfter_Mesh} Mesh / {collidersAfter_Box} Box / {collidersAfter_Cap} Capsule / {collidersAfter_Sph} Sphere.  {optResult}");

            PrefabUtility.SaveAsPrefabAsset(root, prefabPath);
            return prefabPath;
        }
        finally
        {
            if (root != null) UnityEngine.Object.DestroyImmediate(root);
        }
    }

    // -------- Helpers --------

    static Shader FindBestShader()
    {
        RenderPipelineAsset activeRp = GraphicsSettings.currentRenderPipeline;
        string activeRpName = activeRp != null ? activeRp.GetType().Name.ToLowerInvariant() : "";
        if (activeRpName.Contains("hd"))
        {
            Shader s = Shader.Find("HDRP/Lit"); if (s != null) return s;
        }
        if (activeRpName.Contains("universal") || activeRpName.Contains("urp"))
        {
            Shader s = Shader.Find("Universal Render Pipeline/Lit"); if (s != null) return s;
        }
        if (activeRp == null)
        {
            Shader s = Shader.Find("Standard"); if (s != null) return s;
        }
        string[] candidates = { "HDRP/Lit", "Universal Render Pipeline/Lit", "Standard" };
        foreach (string c in candidates) { Shader s = Shader.Find(c); if (s != null) return s; }
        return null;
    }

    static Material FindMaterial(string name)
    {
        if (string.IsNullOrEmpty(name)) return null;
        string[] guids = AssetDatabase.FindAssets(name + " t:Material");
        foreach (string g in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(g);
            Material m = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (m != null && m.name == name) return m;
        }
        return null;
    }

    static void AddColliderAsset(GameObject root, string assetName)
    {
        GameObject model = FindModelAsset(assetName);
        AddColliderModel(root, model);
    }

    static void AddColliderModel(GameObject root, GameObject colModel)
    {
        if (root == null || colModel == null) return;
        MeshFilter colMf = colModel.GetComponentInChildren<MeshFilter>();
        if (colMf == null || colMf.sharedMesh == null)
        {
            Debug.LogWarning($"s4extract: collider model '{colModel.name}' has no MeshFilter/mesh; skipping.");
            return;
        }
        EnsureMeshReadable(colMf.sharedMesh);
        MeshCollider mc = root.AddComponent<MeshCollider>();
        if (mc == null) return;
        mc.sharedMesh = colMf.sharedMesh;
        mc.convex = true;
    }

    static GameObject FindModelAsset(string name)
    {
        if (string.IsNullOrEmpty(name)) return null;
        string[] guids = AssetDatabase.FindAssets(name);
        foreach (string ext in new string[] { ".obj", ".fbx" })
        {
            foreach (string g in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(g);
                if (!path.ToLowerInvariant().EndsWith(ext, StringComparison.Ordinal)) continue;
                GameObject go = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (go != null && (go.name == name || Path.GetFileNameWithoutExtension(path) == name)) return go;
            }
        }
        return null;
    }

    static Texture FindTexture(string nameNoExt)
    {
        if (string.IsNullOrEmpty(nameNoExt)) return null;
        string[] guids = AssetDatabase.FindAssets(nameNoExt + " t:Texture2D");
        foreach (string g in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(g);
            Texture t = AssetDatabase.LoadAssetAtPath<Texture>(path);
            if (t != null && t.name == nameNoExt) return t;
        }
        return null;
    }

    static void MakeNormalMap(Texture tex)
    {
        if (tex == null) return;
        string path = AssetDatabase.GetAssetPath(tex);
        TextureImporter ti = AssetImporter.GetAtPath(path) as TextureImporter;
        if (ti != null && ti.textureType != TextureImporterType.NormalMap)
        {
            ti.textureType = TextureImporterType.NormalMap;
            ti.SaveAndReimport();
        }
    }

    static void EnsureColliderMeshesReadable()
    {
        try
        {
            // Models, not Texture2D – t:Model matches any imported 3D asset.
            string[] guids = AssetDatabase.FindAssets("_collider t:Model");
            foreach (string g in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(g);
                if (string.IsNullOrEmpty(path)) continue;
                ModelImporter mi = AssetImporter.GetAtPath(path) as ModelImporter;
                if (mi == null) continue;
                if (!mi.isReadable)
                {
                    mi.isReadable = true;
                    mi.SaveAndReimport();
                }
            }
        }
        catch (Exception e)
        {
            Debug.LogWarning("s4extract: could not auto-enable Read/Write on some collider meshes: " + e.Message);
        }
    }

    static void EnsureMeshReadable(Mesh mesh)
    {
        if (mesh == null || mesh.isReadable) return;
        try
        {
            string path = AssetDatabase.GetAssetPath(mesh);
            if (string.IsNullOrEmpty(path)) return;
            ModelImporter mi = AssetImporter.GetAtPath(path) as ModelImporter;
            if (mi == null) return;
            mi.isReadable = true;
            mi.SaveAndReimport();
        }
        catch (Exception e)
        {
            Debug.LogWarning($"s4extract: could not enable Read/Write on mesh '{mesh.name}': {e.Message}");
        }
    }

    static MethodInfo FindOptimizeBatchMethod()
    {
        Type optimizerType = null;
        foreach (Assembly asm in AppDomain.CurrentDomain.GetAssemblies())
        {
            Type[] types;
            try { types = asm.GetTypes(); }
            catch (ReflectionTypeLoadException rtle) { types = rtle.Types.Where(t => t != null).ToArray(); }
            catch { continue; }
            foreach (Type t in types)
            {
                if (t == null) continue;
                if (t.Name == OptimizerTypeName && !t.IsGenericType && t.IsClass) { optimizerType = t; break; }
            }
            if (optimizerType != null) break;
        }
        if (optimizerType == null) return null;
        return optimizerType.GetMethod("OptimizeForBatch",
            BindingFlags.Public | BindingFlags.Static,
            null,
            new[] { typeof(GameObject), typeof(float), typeof(float), typeof(float), typeof(float) },
            null);
    }

    static void SetTex(Material m, string prop, Texture t)   { if (m != null && t != null && m.HasProperty(prop)) m.SetTexture(prop, t); }
    static void SetColor(Material m, string prop, Color c)    { if (m != null && m.HasProperty(prop)) m.SetColor(prop, c); }
    static void SetFloat(Material m, string prop, float v)    { if (m != null && m.HasProperty(prop)) m.SetFloat(prop, v); }
}
#endif
