// Auto-generated by s4extract. Batch processor for all exports.
#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.SceneManagement;
using System.IO;
using System.Collections.Generic;
using System.Linq;

[InitializeOnLoad]
public static class S4ExtractBatchFixer
{
    static S4ExtractBatchFixer()
    {
        EditorApplication.delayCall += () => {
            if (EditorPrefs.GetBool("S4Extract_FirstRun", true))
            {
                EditorPrefs.SetBool("S4Extract_FirstRun", false);
                string dataDir = Path.Combine(Application.dataPath, "S4Extract_Data");
                if (Directory.Exists(dataDir))
                {
                    int count = Directory.GetFiles(dataDir, "*.json").Length;
                    if (count > 0)
                        Debug.Log($"s4extract: Batch fixer loaded. Found {count} export(s). Use Tools/s4extract menu.");
                }
            }
        };
    }

    [MenuItem("Tools/s4extract/Fix All Exports")]
    public static void FixAllExports()
    {
        string dataDir = Path.Combine(Application.dataPath, "S4Extract_Data");
        if (!Directory.Exists(dataDir))
        {
            Debug.LogWarning("s4extract: No S4Extract_Data folder found. Export some objects first.");
            return;
        }

        string[] jsonFiles = Directory.GetFiles(dataDir, "*.json");
        if (jsonFiles.Length == 0)
        {
            Debug.LogWarning("s4extract: No export data found.");
            return;
        }

        Debug.Log($"s4extract: Processing {jsonFiles.Length} export(s)...");
        
        int totalFixed = 0;
        int totalAssigned = 0;
        int totalPrefabs = 0;
        
        for (int exportIndex = 0; exportIndex < jsonFiles.Length; exportIndex++)
        {
            string jsonFile = jsonFiles[exportIndex];
            if (EditorUtility.DisplayCancelableProgressBar(
                "s4extract: Fix All Exports",
                $"{exportIndex + 1}/{jsonFiles.Length}  {Path.GetFileNameWithoutExtension(jsonFile)}",
                (float)exportIndex / jsonFiles.Length))
            {
                Debug.LogWarning($"s4extract: Batch cancelled after {exportIndex} export(s).");
                break;
            }
            string stage = "read JSON";
            try
            {
                string json = File.ReadAllText(jsonFile);
                var exportData = JsonUtility.FromJson<ExportData>(json);
                if (exportData == null)
                    throw new System.Exception("JsonUtility returned null ExportData");
                NormalizeExportData(exportData);

                stage = "process materials";
                int fixedCount = ProcessMaterials(exportData);
                stage = "assign materials";
                int assigned = AssignMaterialsToMeshes(exportData);

                stage = "create READY prefab";
                string readyPrefab = CreateReadyPrefab(exportData, jsonFile);

                totalFixed += fixedCount;
                totalAssigned += assigned;
                if (!string.IsNullOrEmpty(readyPrefab)) totalPrefabs++;
            }
            catch (System.Exception e)
            {
                Debug.LogError($"s4extract: Failed to process {Path.GetFileName(jsonFile)} at stage '{stage}':\n{e}");
            }
        }

        EditorUtility.ClearProgressBar();
        AssetDatabase.SaveAssets();
        Debug.Log($"s4extract: Done! Fixed {totalFixed} material(s), assigned {totalAssigned} renderer(s), created {totalPrefabs} prefab(s).");
    }

    [MenuItem("Tools/s4extract/Fix Last Export")]
    public static void FixLastExport()
    {
        string dataDir = Path.Combine(Application.dataPath, "S4Extract_Data");
        if (!Directory.Exists(dataDir))
        {
            Debug.LogWarning("s4extract: No S4Extract_Data folder found.");
            return;
        }

        string[] jsonFiles = Directory.GetFiles(dataDir, "*.json");
        if (jsonFiles.Length == 0)
        {
            Debug.LogWarning("s4extract: No export data found.");
            return;
        }

        string lastFile = jsonFiles.OrderByDescending(f => f).First();

        try
        {
            string json = File.ReadAllText(lastFile);
            var exportData = JsonUtility.FromJson<ExportData>(json);
            if (exportData == null) throw new System.Exception("JsonUtility returned null ExportData");
            NormalizeExportData(exportData);

            int fixedCount = ProcessMaterials(exportData);
            int assigned = AssignMaterialsToMeshes(exportData);
            
            string readyPrefab = CreateReadyPrefab(exportData, lastFile);
            
            AssetDatabase.SaveAssets();
            Debug.Log($"s4extract: Processed {Path.GetFileName(lastFile)}. Fixed {fixedCount} material(s), assigned {assigned} renderer(s).");
        }
        catch (System.Exception e)
        {
            Debug.LogError($"s4extract: Failed: {e.Message}");
        }
    }

    // ========================================================================
    // Data Structures (должны совпадать с JSON)
    // ========================================================================
    
    [System.Serializable]
    public class ExportData
    {
        public string folderName;
        public string id;
        public string assetName;
        public MaterialEntry[] materials;
        public string[] meshNames;
        public string[] colliderAssets;
        public MeshMaterialEntry[] meshMaterials;
    }

    [System.Serializable]
    public class MaterialEntry
    {
        public string materialName;
        public string albedoName;
        public string normalName;
        public string maskName;
    }

    [System.Serializable]
    public class MeshMaterialEntry
    {
        public string meshName;
        public string materialName;
    }

    static void NormalizeExportData(ExportData data)
    {
        if (data.materials == null) data.materials = new MaterialEntry[0];
        if (data.meshNames == null) data.meshNames = new string[0];
        if (data.colliderAssets == null) data.colliderAssets = new string[0];
        if (data.meshMaterials == null) data.meshMaterials = new MeshMaterialEntry[0];
    }

    // ========================================================================
    // Core Processing
    // ========================================================================

    static int ProcessMaterials(ExportData data)
    {
        Shader shader = FindBestShader();
        if (shader == null)
        {
            Debug.LogWarning("s4extract: Could not find suitable shader.");
            return 0;
        }

        int changed = 0;
        foreach (var entry in data.materials)
        {
            Material mat = FindMaterial(entry.materialName);
            Texture albedo = FindTexture(entry.albedoName);
            Texture normal = FindTexture(entry.normalName);
            Texture mask = FindTexture(entry.maskName);
            
            if (mat == null) continue;

            mat.shader = shader;
            if (albedo != null)
            {
                SetTex(mat, "_BaseColorMap", albedo);
                SetTex(mat, "_BaseMap", albedo);
                SetTex(mat, "_MainTex", albedo);
            }
            if (normal != null)
            {
                MakeNormalMap(normal);
                SetTex(mat, "_NormalMap", normal);
                SetTex(mat, "_BumpMap", normal);
                mat.EnableKeyword("_NORMALMAP");
                mat.EnableKeyword("_NORMALMAP_TANGENT_SPACE");
            }
            if (mask != null)
            {
                SetTex(mat, "_MaskMap", mask);
                SetTex(mat, "_MetallicGlossMap", mask);
            }
            
            SetColor(mat, "_BaseColor", Color.white);
            SetColor(mat, "_Color", Color.white);
            SetFloat(mat, "_Metallic", 0f);
            SetFloat(mat, "_Smoothness", 0.5f);
            SetFloat(mat, "_NormalScale", 1f);
            SetFloat(mat, "_BumpScale", 1f);
            SetFloat(mat, "_SurfaceType", 0f);
            SetFloat(mat, "_Surface", 0f);
            mat.renderQueue = -1;
            
            EditorUtility.SetDirty(mat);
            changed++;
        }
        return changed;
    }

    static int AssignMaterialsToMeshes(ExportData data)
    {
        if (data.materials.Length == 0 || data.meshNames.Length == 0) return 0;
        
        Material first = FindMaterial(data.materials[0].materialName);
        if (first == null) return 0;
        
        int assigned = 0;
        
#if UNITY_2023_1_OR_NEWER
        Renderer[] renderers = Object.FindObjectsByType<Renderer>(FindObjectsInactive.Include, FindObjectsSortMode.None);
#else
        Renderer[] renderers = Object.FindObjectsOfType<Renderer>(true);
#endif
        
        foreach (Renderer r in renderers)
        {
            string goName = r.gameObject.name;
            Material target = FindPreferredMaterialForMesh(goName, data);
            
            if (target == null)
            {
                foreach (string mn in data.meshNames)
                {
                    if (goName == mn || goName.StartsWith(mn))
                    {
                        target = FindPreferredMaterialForMesh(mn, data) ?? first;
                        break;
                    }
                }
            }
            
            if (target == null) continue;
            
            Material[] mats = r.sharedMaterials;
            if (mats == null || mats.Length == 0) mats = new Material[] { target };
            for (int i = 0; i < mats.Length; i++) mats[i] = target;
            r.sharedMaterials = mats;
            
            EditorUtility.SetDirty(r);
            assigned++;
        }
        
        return assigned;
    }

    static Material FindPreferredMaterialForMesh(string meshName, ExportData data)
    {
        if (string.IsNullOrEmpty(meshName)) return null;
        foreach (var mm in data.meshMaterials)
        {
            if (meshName == mm.meshName || meshName.StartsWith(mm.meshName))
            {
                Material m = FindMaterial(mm.materialName);
                if (m != null) return m;
            }
        }
        return null;
    }

    // Exporter names models <asset>_lodNN_gNN.  The legacy MODL/MLOD
    // spellings remain accepted so already-exported folders still work.
    static int GetLodIndex(string assetName)
    {
        if (string.IsNullOrEmpty(assetName)) return -1;
        string n = assetName.ToLowerInvariant();
        string[] markers = new string[] { "_lod", "mlod", "modl" };
        foreach (string marker in markers)
        {
            int at = n.LastIndexOf(marker);
            if (at < 0) continue;
            int pos = at + marker.Length;
            int value = 0;
            int digits = 0;
            while (pos < n.Length && n[pos] >= '0' && n[pos] <= '9')
            {
                value = value * 10 + (n[pos] - '0');
                digits++;
                pos++;
            }
            if (digits > 0) return value;
        }
        return -1;
    }

    static string CreateReadyPrefab(ExportData data, string jsonPath)
    {
        if (data.materials.Length == 0 || data.meshNames.Length == 0) return "";
        
        Material first = FindMaterial(data.materials[0].materialName);
        if (first == null) return "";

        string matPath = AssetDatabase.GetAssetPath(first);
        if (string.IsNullOrEmpty(matPath)) return "";
        
        string folder = Path.GetDirectoryName(matPath).Replace("\\", "/");
        string prefabPath = folder + "/" + data.assetName + "_READY.prefab";

        GameObject root = new GameObject(data.assetName + "_READY");
        
        var identity = root.AddComponent<S4Identity>();
        identity.id = int.Parse(string.IsNullOrEmpty(data.id) ? "0" : data.id);
        identity.assetName = data.assetName;
        
        Rigidbody rb = root.GetComponent<Rigidbody>();
        if (rb == null) rb = root.AddComponent<Rigidbody>();
        rb.mass = 10f;
        rb.drag = 0.05f;
        rb.angularDrag = 0.05f;
        rb.useGravity = true;
        rb.isKinematic = false;
        rb.interpolation = RigidbodyInterpolation.Interpolate;
        rb.collisionDetectionMode = CollisionDetectionMode.ContinuousSpeculative;

        int added = 0;
        foreach (string mn in data.meshNames)
        {
            GameObject model = FindModelAsset(mn);
            if (model == null) continue;
            Material target = FindPreferredMaterialForMesh(mn, data) ?? first;
            GameObject child = (GameObject)PrefabUtility.InstantiatePrefab(model);
            if (child == null) child = Object.Instantiate(model);
            child.name = mn;
            child.transform.SetParent(root.transform, false);
            foreach (Renderer r in child.GetComponentsInChildren<Renderer>(true))
            {
                Material[] mats = r.sharedMaterials;
                if (mats == null || mats.Length == 0) mats = new Material[] { target };
                for (int i = 0; i < mats.Length; i++) mats[i] = target;
                r.sharedMaterials = mats;
            }
            added++;
        }

        // Add only the exact collider assets recorded by the current export.
        // Wildcard fallback exists solely for old JSON files.
        if (data.colliderAssets.Length > 0)
        {
            foreach (string colliderAsset in data.colliderAssets)
                AddColliderAsset(root, colliderAsset);
        }
        else
        {
            foreach (string mn in data.meshNames)
            {
                if (GetLodIndex(mn) != 0) continue;
                string[] guids = AssetDatabase.FindAssets(mn + "_collider t:GameObject");
                foreach (string g in guids)
                {
                    string path = AssetDatabase.GUIDToAssetPath(g);
                    if (string.IsNullOrEmpty(path)) continue;
                    GameObject colModel = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                    AddColliderModel(root, colModel);
                }
            }
        }

        // LOD Group
        LODGroup lodGroup = root.AddComponent<LODGroup>();
        var lodRenderers = new Dictionary<int, List<Renderer>>();
        
        foreach (Transform child in root.transform)
        {
            int lodIdx = GetLodIndex(child.name);
            if (lodIdx < 0) continue;

            // An imported FBX may contain several renderers.  Every one must
            // belong to the same LOD, not just the first renderer Unity finds.
            foreach (Renderer r in child.GetComponentsInChildren<Renderer>(true))
            {
                if (!lodRenderers.ContainsKey(lodIdx))
                    lodRenderers[lodIdx] = new List<Renderer>();
                lodRenderers[lodIdx].Add(r);
            }
        }
        
        if (lodRenderers.Count > 0)
        {
            var keys = new List<int>(lodRenderers.Keys);
            keys.Sort();
            
            // The final LOD must have a zero threshold.  Unity otherwise adds
            // its implicit Culled range after the last positive threshold and
            // makes the object disappear at distance.
            LOD[] lods = new LOD[keys.Count];
            float[] screenHeights = new float[] { 0.5f, 0.25f, 0.10f, 0.01f };
            
            for (int i = 0; i < keys.Count; i++)
            {
                int k = keys[i];
                float height = (i == keys.Count - 1)
                    ? 0f
                    : ((i < screenHeights.Length) ? screenHeights[i] : 0.01f);
                lods[i] = new LOD(height, lodRenderers[k].ToArray());
            }
            lodGroup.SetLODs(lods);
            lodGroup.RecalculateBounds();
        }

        if (added == 0)
        {
            Object.DestroyImmediate(root);
            return "";
        }

        // Automatic collider simplification for batch imports. This happens
        // before saving, so every READY prefab is born optimized.
        Debug.LogWarning("s4extract: S4ColliderOptimizer source was not found; keeping convex MeshColliders.");

        PrefabUtility.SaveAsPrefabAsset(root, prefabPath);
        Object.DestroyImmediate(root);
        return prefabPath;
    }

    // ========================================================================
    // Helper Functions
    // ========================================================================

    static Shader FindBestShader()
    {
        string preferred = "hdrp";
        // Prefer the project's active render pipeline. A stale/default
        // exporter flag (especially builtin) otherwise creates magenta assets.
        RenderPipelineAsset activeRp = GraphicsSettings.currentRenderPipeline;
        string activeRpName = activeRp != null ? activeRp.GetType().Name.ToLowerInvariant() : "";
        if (activeRpName.Contains("hd"))
        {
            Shader active = Shader.Find("HDRP/Lit");
            if (active != null) return active;
        }
        if (activeRpName.Contains("universal") || activeRpName.Contains("urp"))
        {
            Shader active = Shader.Find("Universal Render Pipeline/Lit");
            if (active != null) return active;
        }
        if (activeRp == null)
        {
            Shader active = Shader.Find("Standard");
            if (active != null) return active;
        }

        if (preferred == "hdrp")
        {
            Shader s = Shader.Find("HDRP/Lit");
            if (s != null) return s;
        }
        if (preferred == "urp")
        {
            Shader s = Shader.Find("Universal Render Pipeline/Lit");
            if (s != null) return s;
        }
        if (preferred == "builtin")
        {
            Shader s = Shader.Find("Standard");
            if (s != null) return s;
        }

        RenderPipelineAsset rp = GraphicsSettings.currentRenderPipeline;
        string rpName = rp != null ? rp.GetType().Name.ToLowerInvariant() : "";
        if (rpName.Contains("hd"))
        {
            Shader s = Shader.Find("HDRP/Lit");
            if (s != null) return s;
        }
        if (rpName.Contains("universal") || rpName.Contains("urp"))
        {
            Shader s = Shader.Find("Universal Render Pipeline/Lit");
            if (s != null) return s;
        }

        string[] candidates = new string[] { "HDRP/Lit", "Universal Render Pipeline/Lit", "Standard" };
        foreach (string c in candidates)
        {
            Shader s = Shader.Find(c);
            if (s != null) return s;
        }
        return null;
    }

    static Material FindMaterial(string name)
    {
        if (string.IsNullOrEmpty(name)) return null;
        string[] guids = AssetDatabase.FindAssets(name + " t:Material");
        foreach (string g in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(g);
            Material m = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (m != null && m.name == name) return m;
        }
        return null;
    }

    static void AddColliderAsset(GameObject root, string assetName)
    {
        GameObject model = FindModelAsset(assetName);
        AddColliderModel(root, model);
    }

    static void AddColliderModel(GameObject root, GameObject colModel)
    {
        if (root == null || colModel == null) return;
        MeshFilter colMf = colModel.GetComponentInChildren<MeshFilter>();
        if (colMf == null || colMf.sharedMesh == null) return;
        MeshCollider mc = root.AddComponent<MeshCollider>();
        if (mc == null) return;
        mc.sharedMesh = colMf.sharedMesh;
        mc.convex = true;
    }

    static GameObject FindModelAsset(string name)
    {
        if (string.IsNullOrEmpty(name)) return null;
        string[] guids = AssetDatabase.FindAssets(name);

        foreach (string ext in new string[] { ".obj", ".fbx" })
        {
            foreach (string g in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(g);
                if (!path.ToLowerInvariant().EndsWith(ext)) continue;
                GameObject go = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (go != null && (go.name == name || Path.GetFileNameWithoutExtension(path) == name)) return go;
            }
        }
        return null;
    }

    static Texture FindTexture(string nameNoExt)
    {
        if (string.IsNullOrEmpty(nameNoExt)) return null;
        string[] guids = AssetDatabase.FindAssets(nameNoExt + " t:Texture2D");
        foreach (string g in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(g);
            Texture t = AssetDatabase.LoadAssetAtPath<Texture>(path);
            if (t != null && t.name == nameNoExt) return t;
        }
        return null;
    }

    static void MakeNormalMap(Texture tex)
    {
        string path = AssetDatabase.GetAssetPath(tex);
        TextureImporter ti = AssetImporter.GetAtPath(path) as TextureImporter;
        if (ti != null && ti.textureType != TextureImporterType.NormalMap)
        {
            ti.textureType = TextureImporterType.NormalMap;
            ti.SaveAndReimport();
        }
    }

    static void SetTex(Material m, string prop, Texture t)
    {
        if (m.HasProperty(prop)) m.SetTexture(prop, t);
    }

    static void SetColor(Material m, string prop, Color c)
    {
        if (m.HasProperty(prop)) m.SetColor(prop, c);
    }

    static void SetFloat(Material m, string prop, float v)
    {
        if (m.HasProperty(prop)) m.SetFloat(prop, v);
    }
}
#endif
