// Auto-generated by s4extract. Safe to delete after materials are fixed.
#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.SceneManagement;
using System.IO;

[InitializeOnLoad]
public static class S4ExtractMaterialFixer_bd3cc5b3a3
{
    struct Entry
    {
        public string materialName;
        public string albedoName;
        public string normalName;
        public string maskName;
        public Entry(string m, string a, string n, string mask) { materialName = m; albedoName = a; normalName = n; maskName = mask; }
    }

    static readonly Entry[] Entries = new Entry[]
    {
        new Entry("1_swatch00_material", "1_tex00", "1_tex01", "1_tex02"),
        new Entry("1_swatch01_material", "1_tex03", "1_tex01", "1_tex02"),
        new Entry("1_swatch02_material", "1_tex04", "1_tex01", "1_tex02"),
        new Entry("1_swatch03_material", "1_tex05", "1_tex01", "1_tex02"),
        new Entry("1_swatch04_material", "1_tex06", "1_tex01", "1_tex02"),
        new Entry("1_swatch05_material", "1_tex07", "1_tex01", "1_tex02"),
        new Entry("1_swatch06_material", "1_tex08", "1_tex01", "1_tex02"),
        new Entry("1_swatch07_material", "1_tex09", "1_tex01", "1_tex02"),
        new Entry("1_swatch08_material", "1_tex10", "1_tex01", "1_tex02"),
        new Entry("1_swatch09_material", "1_tex11", "1_tex01", "1_tex02"),
    };

    static readonly string[] MeshNames = new string[]
    {
        "1_mlod00_g01",
        "1_mlod00_g02",
    };

    static S4ExtractMaterialFixer_bd3cc5b3a3()
    {
        EditorApplication.delayCall += FixAll;
    }

    [MenuItem("Tools/s4extract/Fix Sims 4 Materials")]
    public static void FixAll()
    {
        Shader shader = FindBestShader();
        if (shader == null)
        {
            Debug.LogWarning("s4extract: could not find HDRP/Lit, URP/Lit or Standard shader in this project.");
            return;
        }

        int changed = 0;
        foreach (Entry e in Entries)
        {
            Material mat = FindMaterial(e.materialName);
            Texture albedo = FindTexture(e.albedoName);
            Texture normal = FindTexture(e.normalName);
            Texture mask = FindTexture(e.maskName);
            if (mat == null) continue;

            mat.shader = shader;
            if (albedo != null)
            {
                SetTex(mat, "_BaseColorMap", albedo); // HDRP
                SetTex(mat, "_BaseMap", albedo);      // URP
                SetTex(mat, "_MainTex", albedo);      // Built-in fallback
            }
            if (normal != null)
            {
                MakeNormalMap(normal);
                SetTex(mat, "_NormalMap", normal); // HDRP
                SetTex(mat, "_BumpMap", normal);   // URP/Built-in
                mat.EnableKeyword("_NORMALMAP");
                mat.EnableKeyword("_NORMALMAP_TANGENT_SPACE");
            }
            if (mask != null)
            {
                SetTex(mat, "_MaskMap", mask);             // HDRP mask map
                SetTex(mat, "_MetallicGlossMap", mask);    // URP/Built-in-ish fallback
            }
            SetColor(mat, "_BaseColor", Color.white);
            SetColor(mat, "_Color", Color.white);
            SetFloat(mat, "_Metallic", 0f);
            SetFloat(mat, "_Smoothness", 0.5f);
            SetFloat(mat, "_NormalScale", 1f);
            SetFloat(mat, "_BumpScale", 1f);
            SetFloat(mat, "_SurfaceType", 0f); // HDRP opaque
            SetFloat(mat, "_Surface", 0f);     // URP opaque
            mat.renderQueue = -1;
            EditorUtility.SetDirty(mat);
            changed++;
        }

        int assigned = AssignFirstMaterialToSceneMeshes();
        string readyPrefab = CreateReadyPrefab();

        if (changed > 0 || assigned > 0 || !string.IsNullOrEmpty(readyPrefab))
        {
            AssetDatabase.SaveAssets();
            Debug.Log("s4extract: fixed " + changed + " material(s), assigned first swatch to " + assigned + " renderer(s), ready prefab: " + readyPrefab + ", shader: " + shader.name);
        }
    }

    static string CreateReadyPrefab()
    {
        if (Entries.Length == 0 || MeshNames.Length == 0) return "";
        Material first = FindMaterial(Entries[0].materialName);
        if (first == null) return "";

        string matPath = AssetDatabase.GetAssetPath(first);
        if (string.IsNullOrEmpty(matPath)) return "";
        string folder = Path.GetDirectoryName(matPath).Replace("\\", "/");
        string prefabPath = folder + "/1_READY.prefab";

        GameObject root = new GameObject("1_READY");
        int added = 0;
        foreach (string mn in MeshNames)
        {
            GameObject model = FindModelAsset(mn);
            if (model == null) continue;
            GameObject child = (GameObject)PrefabUtility.InstantiatePrefab(model);
            if (child == null) child = Object.Instantiate(model);
            child.name = mn;
            child.transform.SetParent(root.transform, false);
            foreach (Renderer r in child.GetComponentsInChildren<Renderer>(true))
            {
                Material[] mats = r.sharedMaterials;
                if (mats == null || mats.Length == 0) mats = new Material[] { first };
                for (int i = 0; i < mats.Length; i++) mats[i] = first;
                r.sharedMaterials = mats;
            }
            added++;
        }

        if (added == 0)
        {
            Object.DestroyImmediate(root);
            return "";
        }

        PrefabUtility.SaveAsPrefabAsset(root, prefabPath);
        Object.DestroyImmediate(root);
        return prefabPath;
    }

    static int AssignFirstMaterialToSceneMeshes()
    {
        if (Entries.Length == 0 || MeshNames.Length == 0) return 0;
        Material first = FindMaterial(Entries[0].materialName);
        if (first == null) return 0;
        int assigned = 0;
#if UNITY_2023_1_OR_NEWER
        Renderer[] renderers = Object.FindObjectsByType<Renderer>(FindObjectsInactive.Include, FindObjectsSortMode.None);
#else
        Renderer[] renderers = Object.FindObjectsOfType<Renderer>(true);
#endif
        foreach (Renderer r in renderers)
        {
            string goName = r.gameObject.name;
            bool match = false;
            foreach (string mn in MeshNames)
            {
                if (goName == mn || goName.StartsWith(mn)) { match = true; break; }
            }
            if (!match) continue;
            Material[] mats = r.sharedMaterials;
            if (mats == null || mats.Length == 0) mats = new Material[] { first };
            for (int i = 0; i < mats.Length; i++) mats[i] = first;
            r.sharedMaterials = mats;
            EditorUtility.SetDirty(r);
            assigned++;
        }
        if (assigned > 0) MarkOpenScenesDirty();
        return assigned;
    }

    static void MarkOpenScenesDirty()
    {
        for (int i = 0; i < SceneManager.sceneCount; i++)
        {
            var scene = SceneManager.GetSceneAt(i);
            if (scene.isLoaded) UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(scene);
        }
    }

    static Shader FindBestShader()
    {
        string preferred = "hdrp";
        if (preferred == "hdrp")
        {
            Shader s = Shader.Find("HDRP/Lit");
            if (s != null) return s;
        }
        if (preferred == "urp")
        {
            Shader s = Shader.Find("Universal Render Pipeline/Lit");
            if (s != null) return s;
        }
        if (preferred == "builtin")
        {
            Shader s = Shader.Find("Standard");
            if (s != null) return s;
        }

        RenderPipelineAsset rp = GraphicsSettings.currentRenderPipeline;
        string rpName = rp != null ? rp.GetType().Name.ToLowerInvariant() : "";
        if (rpName.Contains("hd"))
        {
            Shader s = Shader.Find("HDRP/Lit");
            if (s != null) return s;
        }
        if (rpName.Contains("universal") || rpName.Contains("urp"))
        {
            Shader s = Shader.Find("Universal Render Pipeline/Lit");
            if (s != null) return s;
        }

        string[] candidates = new string[] { "HDRP/Lit", "Universal Render Pipeline/Lit", "Standard" };
        foreach (string c in candidates)
        {
            Shader s = Shader.Find(c);
            if (s != null) return s;
        }
        return null;
    }

    static Material FindMaterial(string name)
    {
        if (string.IsNullOrEmpty(name)) return null;
        string[] guids = AssetDatabase.FindAssets(name + " t:Material");
        foreach (string g in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(g);
            Material m = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (m != null && m.name == name) return m;
        }
        return null;
    }

    static GameObject FindModelAsset(string name)
    {
        if (string.IsNullOrEmpty(name)) return null;
        string[] guids = AssetDatabase.FindAssets(name);

        // Prefer OBJ for the auto-created READY prefab: Unity imports OBJ at
        // 1:1 scale and its face UVs are simple/reliable. FBX is still exported
        // beside it for external tools, but Unity's FBX importer may apply a
        // 0.01 file scale depending on FBX unit metadata.
        foreach (string ext in new string[] { ".obj", ".fbx" })
        {
            foreach (string g in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(g);
                if (!path.ToLowerInvariant().EndsWith(ext)) continue;
                GameObject go = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (go != null && (go.name == name || Path.GetFileNameWithoutExtension(path) == name)) return go;
            }
        }
        return null;
    }

    static Texture FindTexture(string nameNoExt)
    {
        if (string.IsNullOrEmpty(nameNoExt)) return null;
        string[] guids = AssetDatabase.FindAssets(nameNoExt + " t:Texture2D");
        foreach (string g in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(g);
            Texture t = AssetDatabase.LoadAssetAtPath<Texture>(path);
            if (t != null && t.name == nameNoExt) return t;
        }
        return null;
    }

    static void MakeNormalMap(Texture tex)
    {
        string path = AssetDatabase.GetAssetPath(tex);
        TextureImporter ti = AssetImporter.GetAtPath(path) as TextureImporter;
        if (ti != null && ti.textureType != TextureImporterType.NormalMap)
        {
            ti.textureType = TextureImporterType.NormalMap;
            ti.SaveAndReimport();
        }
    }

    static void SetTex(Material m, string prop, Texture t)
    {
        if (m.HasProperty(prop)) m.SetTexture(prop, t);
    }

    static void SetColor(Material m, string prop, Color c)
    {
        if (m.HasProperty(prop)) m.SetColor(prop, c);
    }

    static void SetFloat(Material m, string prop, float v)
    {
        if (m.HasProperty(prop)) m.SetFloat(prop, v);
    }
}
#endif
